Physprep docs
courtois-neuromod/cneuromod_docs pull request #123
Opened 2023-08-04 20:07 UTC by me-pic

PR related to #122

2023-08-04 20:07 UTC, me-pic commented
@bpinsard @julieaboyle1 @sangfrois

2023-08-04 20:25 UTC, sangfrois commented
Thanks for getting the ball rolling Marie. I will look into this ASAP

2023-08-07 18:18 UTC, me-pic commented
@sangfrois For the quality assessment of the cardiac signals: setting the threshold for the std of the RR intervals to 300 seems a bit too liberal. Should this criterion be revised ?

2023-08-09 17:23 UTC, sangfrois commented
I do not see any clear physiological rationale as to where this threshold should lie. I worry we might discard valid segments. I'm opened to suggestions.

2023-08-11 17:43 UTC, sangfrois commented
[You can track my changes here, as i cannot push on your branch :)](https://github.com/sangfrois/cneuromod_docs/tree/me-pic/physprep_docs)

2024-03-20 15:51 UTC, me-pic commented
I'll have to make sure everything is up to date before it is officially ready to be reviewed !

2025-01-29 22:44 UTC, pbellec commented
@me-pic is that ready review / merge?

2025-01-31 16:17 UTC, bpinsard commented
@me-pic please rebase on main for the build to work.

2025-02-07 17:17 UTC, me-pic commented
@pbellec @bpinsard @julieaboyle1 Physio doc ready to be reviewed !

2025-10-09 13:45 UTC, lunebellec requested changes

2025-10-09 13:45 UTC, lunebellec commented on source/DERIVATIVES.md
> +The physiological data were preprocessed using a pipeline developed within the lab, called Physprep.
which lab? cneuromod? is there a repo? docs?

2025-10-09 13:45 UTC, lunebellec commented on source/DERIVATIVES.md
> +The workflow developed to process the physiological data is based on Phys2Bids 2.8.3; Scipy 1.9.0; Neurokit2 0.2.3;
I think it would be better to point to the file in the derivatives where we can find the specific versions of the dependencies. For a paper, it makes sense to hard-code the version. But we don't necessarily want to revisit the docs every time we make an update.

2025-10-09 13:45 UTC, lunebellec commented on source/DERIVATIVES.md
> +: The EDA filtering procedure was implemented as per [NeuroKit2 default EDA cleaning method](https://neuropsychology.github.io/NeuroKit/functions/eda.html#preprocessing). Since EDA signal is characte
I suggest "we did not apply a highpass filter to retain the tonic component" instead of "we refrained" which sounds a bit weird in this context. Also, you may want to briefly indicate why you did not implement this correction.

2025-10-09 13:46 UTC, lunebellec commented
this is awesome @me-pic !! I have left a few minor comments and it's ready to be merged.

2025-10-09 15:07 UTC, me-pic commented
Thank you @lunebellec for your feedback :smile_cat: I'll make the changes ASAP !

2026-05-08 14:53 UTC, lunebellec commented
There is a major refactor of the docs ongoing. This content will be merged into the new home of the docs, `cneuromod.all`, as part of this branch https://github.com/courtois-neuromod/cneuromod.all/tree/issue1_docs_integration

2026-05-08 14:53 UTC, closed without merging