add a description of the anatomical dataset
courtois-neuromod/cneuromod_docs pull request #73
Opened 2022-07-07 16:02 UTC by bpinsard

2022-07-07 16:11 UTC, pbellec requested changes

2022-07-07 16:11 UTC, pbellec commented on source/DATASETS.md
> +The anatomical dataset intends to acquire longitudinal anatomical image of the brain and upper spinal cord at an approximate rate of 4 sessions a year.
```suggestion
The anatomical dataset includes longitudinal anatomical images of the brain and upper spinal cord at an approximate rate of 4 sessions a year. The primary intended use of this dataset is to monitor the structural stability of the brain of participants for the duration of the study. Many quantitative measures of brain structure can also be derived and included in analyses, such as gray matter morphometry, tractography or measures of myelination. 
```

2022-07-07 16:11 UTC, pbellec commented on source/DATASETS.md
> +The MRI sequences are described in more detailed in :ref:`Brain anatomical sequences` :ref:`Spinal cord anatomical sequences`, including pdfs of the Siemens exam cards.
Maybe include a high level summary of all sequences here (I am thinking of a one-liner).

2022-07-07 16:11 UTC, pbellec commented on source/DATASETS.md
> +Brain T1w, T2w and DWI were copied from the HCP aging and development protocol for Prisma MRI scanner.
Maybe add something like "Other sequences were selected and optimized by the Courtois NeuroMod team."

2022-07-07 16:11 UTC, pbellec commented on source/DATASETS.md
> +All images covering the face were anonymized by zeroing the data in the face, teeth and ears regions with a custom mask warped from the MNI space based on a linear registration of the T1w brain MRI s
maybe link the tool / script which was used.

2022-07-07 21:01 UTC, pbellec approved these changes

2022-07-08 16:00 UTC, julieaboyle1 approved these changes

2022-07-08 16:01 UTC, merged