Update DATASETS.md
courtois-neuromod/cneuromod_docs pull request #94
Opened 2022-12-21 21:44 UTC by julieaboyle1

added subject info ( both N and IDs) for harrypotter, shinobi_training

2022-12-21 23:54 UTC, hyruuk approved these changes

2022-12-21 23:57 UTC, hyruuk requested changes
We might want to remove the few sessions of sub-03 to stay consistent with the doc ? Or adjust the doc accordingly

2022-12-22 15:46 UTC, julieaboyle1 commented
> 

agreed @hyruuk, can how many data points do we have for sub-03?

2022-12-22 16:06 UTC, hyruuk commented
We have about ~20 .bk2 files for sub-03, vs hundreds for the other subjects.

2023-01-13 22:07 UTC, pbellec commented
LGTM. 

Please make a decision on the point raised by @hyruuk

2023-01-13 22:07 UTC, pbellec approved these changes

2025-01-29 22:56 UTC, merged